### ISSUE TITLE
module 'petab' has no attribute 'get_optimization_to_simulation_scale_mapping'

### ISSUE THREAD

**Issue by afvillaverde** [ICB-DCM/pyPESTO#250]
I get an error when trying to build the objective function using pyPESTO's petab import. I am using the latest versions of PEtab (0.1.4) and pyPESTO (0.0.10). I didn't get this error with older versions (at least it worked with PEtab 0.0.0a16 and pyPESTO 0.0.8). My code is:

```
petab_problem = petab.Problem.from_folder(folder_base + model_name)
importer = pypesto.PetabImporter(petab_problem)
obj = importer.create_objective()
```

The last line of the code above gives the following error:

~/anaconda3/envs/ENV_AMICI2/lib/python3.7/site-packages/pypesto/objective/petab_import.py in create_objective(self, model, solver, edatas, force_compile)
    356 
    357         scale_mappings = \
--> 358             petab.get_optimization_to_simulation_scale_mapping(
    359                 parameter_df=self.petab_problem.parameter_df,
    360                 mapping_par_opt_to_par_sim=parameter_mappings,

AttributeError: module 'petab' has no attribute 'get_optimization_to_simulation_scale_mapping'

**Comment by yannikschaelte** [comment]
Hi @afvillaverde . Yes, we had to rewrite part of that functionality in petab recently, sorry for that. The latest version of pypesto where that is fixed is actually 0.0.11. I am right now not sure it that's on pypi, because they seem to have a downtime, but you can install from git directly via ``pip install git+https://github.com/icb-dcm/pypesto.git``

I hope it works with that one, otherwise please let us know. This week, there will actually be a new release of AMICI and pyPESTO with some more bugfixes.

**Comment by yannikschaelte** [comment]
@afvillaverde checked: on pypi also pypesto 0.0.11 is available, installable via ``pip install --upgrade pypesto``. does the issue still exist for you?

**Comment by afvillaverde** [comment]
Issue solved!
