### ISSUE TITLE
`ReturnDataReportingMode` not handled correctly for `AggregatedObjective`

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/pyPESTO#857]
`AggregatedObjective` calls `call_unprocessed`, not `__call__`, so then handling via `__call__` introduced in #835 doesn't have any effect and rdata will not be fully populated.

**Comment by dweindl** [comment]
Not sure how to handle that, as `AggregatedObjective` is not really AMICI-aware, besides checking for `result[RDATAS]` in `aggregate_results`. Not using it, but my feeling is that using `AggregatedObjective.call(..., amici_reporting=amici.RDataReporting.full)` would be the most sensible thing to do, if the full output is required.

**Comment by FFroehlich** [comment]
> Not sure how to handle that, as `AggregatedObjective` is not really AMICI-aware, besides checking for `result[RDATAS]` in `aggregate_results`.

I agree, didn't see an easy way to handle it.

> Not using it, but my feeling is that using `AggregatedObjective.call(..., amici_reporting=amici.RDataReporting.full)` would be the most sensible thing to do, if the full output is required.

Yes, that's my current workaround, but would be nice to introduce some automatic handling.

**Comment by shoepfl** [comment]
Hi Fabian and Daniel,

I think I encountered the problem you describe above when I use nonuniform objective priors and want to create an ensemble thereafter.

I get the error:
    state_ids = amici_objective.amici_model.getStateIds()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AggregatedObjective' object has no attribute 'amici_model'

this works all just fine when I use the default uniform priors.

Could you please elaborate the workaround a little more in detail so that I can also apply it.


Thanks and best,
Sebastian

**Comment by dweindl** [comment]
Hi @shoepfl, to better understand the problem, could you please share the full error traceback?

**Comment by shoepfl** [comment]
Thanks, the problem is indeed because the ensemble got the `AggregatedObjective` instead of `AmiciObjective`.

Upon selecting the `AmiciObjective` object from the `AggregatedObjective` via `amici_objective = result.problem.objective._objectives[0]` I got problems with the paramter mapping:

[Parameter_mapping_error_AggregatedObjective.txt](https://github.com/ICB-DCM/pyPESTO/files/13425916/Parameter_mapping_error_AggregatedObjective.txt)

the `p0` Parameter is in the PEtab file but not estimated. Probably it is hard to tell for you without having the code that produces the error. If it helps I can create a small example model which reproduces the error.

**Comment by FFroehlich** [comment]
the parameter mapping is probably added as the preprocessor to the `AggregatedObjective`, so if you run the ensemble on the amici objective, the preprocessor no longer runs. sounds like this needs to be fixed in the ensemble code rather than in your script.

**Comment by shoepfl** [comment]
Indeed it seems like a general problem in the code for the ensemble creation.

**Comment by shoepfl** [comment]
Is there a workaround for the meantime? My idea was to manually replace the 'AggregatedObjective' in the hdf5 file with the 'AmiciObjective' but I fail running the ensemble creation code with a stored result.

Here the `result.problem.objective` from `result = store.read_result(f"{hdf5_filename}.hdf5", problem=True)`  seems to be not an amici objective and therefore does not have this attribute.
